Building DAG of jobs...
Provided cores: 32
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	4	AnalyzeCovariates_MT
	4	AnalyzeCovariates_genome
	4	BaseRecal_MT
	4	BaseRecal_genome
	4	IndelRealigner_MT
	4	IndelRealigner_genome
	3	KeepOnlyVariants
	3	MergeMutectVarscan
	3	MergeWriteVariants
	3	MutectSplitVariants
	4	PostRecalTable_MT
	4	PostRecalTable_genome
	4	PrintReads_MT
	4	PrintReads_genome
	4	RTC_MT
	4	RTC_genome
	3	Remove_segdups
	3	VarscanSplitVariants
	1	all
	3	annovar_MT_mutect
	3	annovar_MT_varscan
	3	annovar_genome_mutect
	3	annovar_genome_varscan
	3	checkMAFs
	3	create_rsID_table
	4	extractUnmapped_convert
	4	extractUnmapped_extract
	1	fastqc_trimmed_R1
	1	fastqc_trimmed_R2
	3	filterExonicPolymorphic
	3	filterSomatic_Indel
	3	filterSomatic_SNV
	4	indexing_MT
	4	indexing_genome
	4	map_to_MT
	3	map_to_exome
	3	map_to_genome
	4	marking_MT
	4	marking_genome
	3	muTect_MT
	3	muTect_genome
	4	sorting_MT
	4	sorting_exome
	4	sorting_genome
	3	varscan_MT_patient
	4	varscan_MT_sample
	3	varscan_genome_patient
	4	varscan_genome_sample
	162

Job 276: >> C0017S : sorting exome


Job 281: >> B2002D : Aligning to reference EXOME


Job 199: >> B2002D : Aligning to reference NUCLEAR GENOME


Job 218: >> C0017S : Aligning to reference NUCLEAR GENOME


Job 2: >> B2002D : fastqc1 on trimmed fastq
Activating conda environment /home/PERSONALE/eugenio.fonzi2/WESPipeline/.snakemake/conda/e35b1969.
Activating conda environment /home/PERSONALE/eugenio.fonzi2/WESPipeline/.snakemake/conda/e35b1969.
Activating conda environment /home/PERSONALE/eugenio.fonzi2/WESPipeline/.snakemake/conda/e35b1969.

Activating conda environment /home/PERSONALE/eugenio.fonzi2/WESPipeline/.snakemake/conda/e35b1969.
Activating conda environment /home/PERSONALE/eugenio.fonzi2/WESPipeline/.snakemake/conda/e35b1969.

Job 278: >> C0017D : Aligning to reference EXOME

Activating conda environment /home/PERSONALE/eugenio.fonzi2/WESPipeline/.snakemake/conda/e35b1969.

Job 163: >> C0017D : sorting genome

Activating conda environment /home/PERSONALE/eugenio.fonzi2/WESPipeline/.snakemake/conda/e35b1969.

Job 208: >> A1015Dbis : Aligning to reference NUCLEAR GENOME

Activating conda environment /home/PERSONALE/eugenio.fonzi2/WESPipeline/.snakemake/conda/e35b1969.

Job 11: >> B2002D : fastqc2 on trimmed fastq

Activating conda environment /home/PERSONALE/eugenio.fonzi2/WESPipeline/.snakemake/conda/e35b1969.

Job 277: >> A1015Dbis : Aligning to reference EXOME

Activating conda environment /home/PERSONALE/eugenio.fonzi2/WESPipeline/.snakemake/conda/e35b1969.
Waiting at most 5 seconds for missing files.
Will exit after finishing currently running jobs.
Waiting at most 5 seconds for missing files.
Will exit after finishing currently running jobs.
Error in rule map_to_exome:
    jobid: 281
    output: /home/PERSONALE/eugenio.fonzi2/ANALYSES_WES/180105_test_adapters_NO_on_clean/04_alignment_exome/01_intermediate/B2002D.sam
    log: /home/PERSONALE/eugenio.fonzi2/ANALYSES_WES/180105_test_adapters_NO_on_clean/04_alignment_exome/logs/B2002D_alignment.log

RuleException:
CalledProcessError in line 831 of /home/PERSONALE/eugenio.fonzi2/WESPipeline/snakefile_04.py:
Command 'source activate /home/PERSONALE/eugenio.fonzi2/WESPipeline/.snakemake/conda/e35b1969; set -euo pipefail;  bwa mem -M -t 4 -R '@RG\tID:B2002D\tSM:B2002D\tPL:illumina\tLB:truseq\tPU:PE' /home/PERSONALE/eugenio.fonzi2/data_ref/truseq.fasta /home/PERSONALE/eugenio.fonzi2/ANALYSES_WES/180105_test_adapters_NO_on_clean/02_fastq_trimmed/B2002D_R1.fastq /home/PERSONALE/eugenio.fonzi2/ANALYSES_WES/180105_test_adapters_NO_on_clean/02_fastq_trimmed/B2002D_R2.fastq > /home/PERSONALE/eugenio.fonzi2/ANALYSES_WES/180105_test_adapters_NO_on_clean/04_alignment_exome/01_intermediate/B2002D.sam 2> /home/PERSONALE/eugenio.fonzi2/ANALYSES_WES/180105_test_adapters_NO_on_clean/04_alignment_exome/logs/B2002D_alignment.log ' returned non-zero exit status 1.
  File "/home/PERSONALE/eugenio.fonzi2/WESPipeline/snakefile_04.py", line 831, in __rule_map_to_exome
  File "/home/PERSONALE/eugenio.fonzi2/miniconda3/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Removing output files of failed job map_to_exome since they might be corrupted:
/home/PERSONALE/eugenio.fonzi2/ANALYSES_WES/180105_test_adapters_NO_on_clean/04_alignment_exome/01_intermediate/B2002D.sam
Error in rule map_to_genome:
    jobid: 208
    output: /home/PERSONALE/eugenio.fonzi2/ANALYSES_WES/180105_test_adapters_NO_on_clean/03_alignment_genome/01_intermediate/A1015Dbis.sam
    log: /home/PERSONALE/eugenio.fonzi2/ANALYSES_WES/180105_test_adapters_NO_on_clean/03_alignment_genome/logs/A1015Dbis_alignment.log

RuleException:
CalledProcessError in line 566 of /home/PERSONALE/eugenio.fonzi2/WESPipeline/snakefile_04.py:
Command 'source activate /home/PERSONALE/eugenio.fonzi2/WESPipeline/.snakemake/conda/e35b1969; set -euo pipefail;  bwa mem -M -t 4 -R '@RG\tID:A1015Dbis\tSM:A1015Dbis\tPL:illumina\tLB:truseq\tPU:PE' /home/PERSONALE/eugenio.fonzi2/data_ref/human_g1k_v37.fasta /home/PERSONALE/eugenio.fonzi2/ANALYSES_WES/180105_test_adapters_NO_on_clean/02_fastq_trimmed/A1015Dbis_R1.fastq /home/PERSONALE/eugenio.fonzi2/ANALYSES_WES/180105_test_adapters_NO_on_clean/02_fastq_trimmed/A1015Dbis_R2.fastq > /home/PERSONALE/eugenio.fonzi2/ANALYSES_WES/180105_test_adapters_NO_on_clean/03_alignment_genome/01_intermediate/A1015Dbis.sam 2> /home/PERSONALE/eugenio.fonzi2/ANALYSES_WES/180105_test_adapters_NO_on_clean/03_alignment_genome/logs/A1015Dbis_alignment.log ' returned non-zero exit status 1.
  File "/home/PERSONALE/eugenio.fonzi2/WESPipeline/snakefile_04.py", line 566, in __rule_map_to_genome
  File "/home/PERSONALE/eugenio.fonzi2/miniconda3/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Removing output files of failed job map_to_genome since they might be corrupted:
/home/PERSONALE/eugenio.fonzi2/ANALYSES_WES/180105_test_adapters_NO_on_clean/03_alignment_genome/01_intermediate/A1015Dbis.sam
Will exit after finishing currently running jobs.
Will exit after finishing currently running jobs.
Error in rule map_to_genome:
    jobid: 199
    output: /home/PERSONALE/eugenio.fonzi2/ANALYSES_WES/180105_test_adapters_NO_on_clean/03_alignment_genome/01_intermediate/B2002D.sam
    log: /home/PERSONALE/eugenio.fonzi2/ANALYSES_WES/180105_test_adapters_NO_on_clean/03_alignment_genome/logs/B2002D_alignment.log

RuleException:
CalledProcessError in line 566 of /home/PERSONALE/eugenio.fonzi2/WESPipeline/snakefile_04.py:
Command 'source activate /home/PERSONALE/eugenio.fonzi2/WESPipeline/.snakemake/conda/e35b1969; set -euo pipefail;  bwa mem -M -t 4 -R '@RG\tID:B2002D\tSM:B2002D\tPL:illumina\tLB:truseq\tPU:PE' /home/PERSONALE/eugenio.fonzi2/data_ref/human_g1k_v37.fasta /home/PERSONALE/eugenio.fonzi2/ANALYSES_WES/180105_test_adapters_NO_on_clean/02_fastq_trimmed/B2002D_R1.fastq /home/PERSONALE/eugenio.fonzi2/ANALYSES_WES/180105_test_adapters_NO_on_clean/02_fastq_trimmed/B2002D_R2.fastq > /home/PERSONALE/eugenio.fonzi2/ANALYSES_WES/180105_test_adapters_NO_on_clean/03_alignment_genome/01_intermediate/B2002D.sam 2> /home/PERSONALE/eugenio.fonzi2/ANALYSES_WES/180105_test_adapters_NO_on_clean/03_alignment_genome/logs/B2002D_alignment.log ' returned non-zero exit status 1.
  File "/home/PERSONALE/eugenio.fonzi2/WESPipeline/snakefile_04.py", line 566, in __rule_map_to_genome
  File "/home/PERSONALE/eugenio.fonzi2/miniconda3/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Removing output files of failed job map_to_genome since they might be corrupted:
/home/PERSONALE/eugenio.fonzi2/ANALYSES_WES/180105_test_adapters_NO_on_clean/03_alignment_genome/01_intermediate/B2002D.sam
Error in rule sorting_exome:
    jobid: 276
    output: /home/PERSONALE/eugenio.fonzi2/ANALYSES_WES/180105_test_adapters_NO_on_clean/04_alignment_exome/01_intermediate/C0017S_sorted.bam
    log: /home/PERSONALE/eugenio.fonzi2/ANALYSES_WES/180105_test_adapters_NO_on_clean/04_alignment_exome/logs/C0017S_sorting.log

RuleException:
CalledProcessError in line 852 of /home/PERSONALE/eugenio.fonzi2/WESPipeline/snakefile_04.py:
Command 'source activate /home/PERSONALE/eugenio.fonzi2/WESPipeline/.snakemake/conda/e35b1969; set -euo pipefail;  java -jar /home/PERSONALE/eugenio.fonzi2/softwares/picard-tools-1.119/SortSam.jar INPUT=/home/PERSONALE/eugenio.fonzi2/ANALYSES_WES/180105_test_adapters_NO_on_clean/04_alignment_exome/01_intermediate/C0017S.sam OUTPUT=/home/PERSONALE/eugenio.fonzi2/ANALYSES_WES/180105_test_adapters_NO_on_clean/04_alignment_exome/01_intermediate/C0017S_sorted.bam SORT_ORDER=coordinate TMP_DIR=/home/PERSONALE/eugenio.fonzi2/ANALYSES_WES/180105_test_adapters_NO_on_clean/tmp/ 2> /home/PERSONALE/eugenio.fonzi2/ANALYSES_WES/180105_test_adapters_NO_on_clean/04_alignment_exome/logs/C0017S_sorting.log ' returned non-zero exit status 1.
  File "/home/PERSONALE/eugenio.fonzi2/WESPipeline/snakefile_04.py", line 852, in __rule_sorting_exome
  File "/home/PERSONALE/eugenio.fonzi2/miniconda3/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Error in rule map_to_genome:
    jobid: 218
    output: /home/PERSONALE/eugenio.fonzi2/ANALYSES_WES/180105_test_adapters_NO_on_clean/03_alignment_genome/01_intermediate/C0017S.sam
    log: /home/PERSONALE/eugenio.fonzi2/ANALYSES_WES/180105_test_adapters_NO_on_clean/03_alignment_genome/logs/C0017S_alignment.log

RuleException:
CalledProcessError in line 566 of /home/PERSONALE/eugenio.fonzi2/WESPipeline/snakefile_04.py:
Command 'source activate /home/PERSONALE/eugenio.fonzi2/WESPipeline/.snakemake/conda/e35b1969; set -euo pipefail;  bwa mem -M -t 4 -R '@RG\tID:C0017S\tSM:C0017S\tPL:illumina\tLB:truseq\tPU:PE' /home/PERSONALE/eugenio.fonzi2/data_ref/human_g1k_v37.fasta /home/PERSONALE/eugenio.fonzi2/ANALYSES_WES/180105_test_adapters_NO_on_clean/02_fastq_trimmed/C0017S_R1.fastq /home/PERSONALE/eugenio.fonzi2/ANALYSES_WES/180105_test_adapters_NO_on_clean/02_fastq_trimmed/C0017S_R2.fastq > /home/PERSONALE/eugenio.fonzi2/ANALYSES_WES/180105_test_adapters_NO_on_clean/03_alignment_genome/01_intermediate/C0017S.sam 2> /home/PERSONALE/eugenio.fonzi2/ANALYSES_WES/180105_test_adapters_NO_on_clean/03_alignment_genome/logs/C0017S_alignment.log ' returned non-zero exit status 1.
  File "/home/PERSONALE/eugenio.fonzi2/WESPipeline/snakefile_04.py", line 566, in __rule_map_to_genome
  File "/home/PERSONALE/eugenio.fonzi2/miniconda3/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Error in rule map_to_exome:
    jobid: 278
    output: /home/PERSONALE/eugenio.fonzi2/ANALYSES_WES/180105_test_adapters_NO_on_clean/04_alignment_exome/01_intermediate/C0017D.sam
    log: /home/PERSONALE/eugenio.fonzi2/ANALYSES_WES/180105_test_adapters_NO_on_clean/04_alignment_exome/logs/C0017D_alignment.log

RuleException:
CalledProcessError in line 831 of /home/PERSONALE/eugenio.fonzi2/WESPipeline/snakefile_04.py:
Command 'source activate /home/PERSONALE/eugenio.fonzi2/WESPipeline/.snakemake/conda/e35b1969; set -euo pipefail;  bwa mem -M -t 4 -R '@RG\tID:C0017D\tSM:C0017D\tPL:illumina\tLB:truseq\tPU:PE' /home/PERSONALE/eugenio.fonzi2/data_ref/truseq.fasta /home/PERSONALE/eugenio.fonzi2/ANALYSES_WES/180105_test_adapters_NO_on_clean/02_fastq_trimmed/C0017D_R1.fastq /home/PERSONALE/eugenio.fonzi2/ANALYSES_WES/180105_test_adapters_NO_on_clean/02_fastq_trimmed/C0017D_R2.fastq > /home/PERSONALE/eugenio.fonzi2/ANALYSES_WES/180105_test_adapters_NO_on_clean/04_alignment_exome/01_intermediate/C0017D.sam 2> /home/PERSONALE/eugenio.fonzi2/ANALYSES_WES/180105_test_adapters_NO_on_clean/04_alignment_exome/logs/C0017D_alignment.log ' returned non-zero exit status 1.
  File "/home/PERSONALE/eugenio.fonzi2/WESPipeline/snakefile_04.py", line 831, in __rule_map_to_exome
  File "/home/PERSONALE/eugenio.fonzi2/miniconda3/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Error in rule sorting_genome:
    jobid: 163
    output: /home/PERSONALE/eugenio.fonzi2/ANALYSES_WES/180105_test_adapters_NO_on_clean/03_alignment_genome/01_intermediate/C0017D_sorted.bam
    log: /home/PERSONALE/eugenio.fonzi2/ANALYSES_WES/180105_test_adapters_NO_on_clean/03_alignment_genome/logs/C0017D_sorting.log

RuleException:
CalledProcessError in line 587 of /home/PERSONALE/eugenio.fonzi2/WESPipeline/snakefile_04.py:
Command 'source activate /home/PERSONALE/eugenio.fonzi2/WESPipeline/.snakemake/conda/e35b1969; set -euo pipefail;  java -jar /home/PERSONALE/eugenio.fonzi2/softwares/picard-tools-1.119/SortSam.jar INPUT=/home/PERSONALE/eugenio.fonzi2/ANALYSES_WES/180105_test_adapters_NO_on_clean/03_alignment_genome/01_intermediate/C0017D.sam OUTPUT=/home/PERSONALE/eugenio.fonzi2/ANALYSES_WES/180105_test_adapters_NO_on_clean/03_alignment_genome/01_intermediate/C0017D_sorted.bam SORT_ORDER=coordinate TMP_DIR=/home/PERSONALE/eugenio.fonzi2/ANALYSES_WES/180105_test_adapters_NO_on_clean/tmp/ 2> /home/PERSONALE/eugenio.fonzi2/ANALYSES_WES/180105_test_adapters_NO_on_clean/03_alignment_genome/logs/C0017D_sorting.log ' returned non-zero exit status 1.
  File "/home/PERSONALE/eugenio.fonzi2/WESPipeline/snakefile_04.py", line 587, in __rule_sorting_genome
  File "/home/PERSONALE/eugenio.fonzi2/miniconda3/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Removing output files of failed job sorting_exome since they might be corrupted:
/home/PERSONALE/eugenio.fonzi2/ANALYSES_WES/180105_test_adapters_NO_on_clean/04_alignment_exome/01_intermediate/C0017S_sorted.bam
Removing output files of failed job map_to_genome since they might be corrupted:
/home/PERSONALE/eugenio.fonzi2/ANALYSES_WES/180105_test_adapters_NO_on_clean/03_alignment_genome/01_intermediate/C0017S.sam
Removing output files of failed job map_to_exome since they might be corrupted:
/home/PERSONALE/eugenio.fonzi2/ANALYSES_WES/180105_test_adapters_NO_on_clean/04_alignment_exome/01_intermediate/C0017D.sam
Removing output files of failed job sorting_genome since they might be corrupted:
/home/PERSONALE/eugenio.fonzi2/ANALYSES_WES/180105_test_adapters_NO_on_clean/03_alignment_genome/01_intermediate/C0017D_sorted.bam
Will exit after finishing currently running jobs.
Will exit after finishing currently running jobs.
Will exit after finishing currently running jobs.
Will exit after finishing currently running jobs.
Will exit after finishing currently running jobs.
Finished job 277.
1 of 162 steps (0.62%) done
Will exit after finishing currently running jobs.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2018-01-10T084318.954509.snakemake.log
